version: "3"

services:
  catalog_db_test:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: catalog_db_password
      POSTGRES_DB: catalog_test
    volumes:
      - ./db-data/catalog_db_postgres/:/var/lib/postgresql/data
  order_db_test:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: order_db_password
      POSTGRES_DB: order_test
    volumes:
      - ./db-data/order_db_postgres/:/var/lib/postgresql/data
